import React,{useState}from"react";
import{createRoot}from"react-dom/client";
import"./styles.css";

const courses=[
{id:1,title:"أساسيات البرمجة بلغة بايثون",cat:"برمجة",level:"مبتدئ",lessons:18,duration:"4س 30د",progress:43,color:"#1b3f80"},
{id:2,title:"تحليل البيانات باستخدام Python",cat:"تحليل البيانات",level:"متوسط",lessons:24,duration:"7س 10د",progress:18,color:"#4a347b"},
{id:3,title:"مقدمة في الذكاء الاصطناعي",cat:"ذكاء اصطناعي",level:"متوسط",lessons:20,duration:"6س 20د",progress:0,color:"#315f69"},
{id:4,title:"JavaScript وتطوير الويب",cat:"تطوير الويب",level:"مبتدئ",lessons:22,duration:"5س 45د",progress:72,color:"#6b4a22"}
];
const lessons=[["✓","08:15","ما هي البرمجة؟"],["✓","12:40","بيئة العمل والمتغيرات"],["▶","10:00","الحلقات التكرارية"],["🔒","15:20","الدوال والقوائم"],["🔒","18:05","المشاريع والتطبيق العملي"]];
const questions=[
{q:"ما هو الناتج الصحيح لتنفيذ الكود البرمجي التالي؟",code:'for i in range(1, 4):\\n    print(i, end="-")',a:["1-2-3-4-","1-2-3-","1-2-","0-1-2-3-"],correct:1},
{q:"أي كلمة تستخدم لتعريف دالة في Python؟",code:"_____ greet(name):\\n    return name",a:["func","def","function","method"],correct:1},
{q:"ما نوع القيمة الناتجة من len([1,2,3])؟",code:"x = len([1, 2, 3])\\nprint(type(x))",a:["str","float","int","list"],correct:2}
];

function Header({go,active="الرئيسية"}){
 const links=[["الرئيسية","/"],["الدورات","/catalog"],["المنح والفرص","/scholarships"],["الفعاليات","/events"],["المسابقات","/competitions"]];
 return <header className="header"><div className="actions"><button className="iconBtn">◯</button><button className="iconBtn">♢<i/></button><button className="iconBtn">⌕</button></div><nav>{links.map(([t,p])=><button className={active===t?"active":""} onClick={()=>go(p)} key={t}>{t}</button>)}</nav><button className="brand" onClick={()=>go("/")}><span>أكاديمية خوارزم</span><b>خ</b></button></header>
}
function BottomNav({go,active="/"}){return <div className="bottomNav">{[["⌂","الرئيسية","/"],["▦","لوحتي","/dashboard"],["▤","الدورات","/catalog"],["✦","المنح","/scholarships"],["◯","حسابي","/profile"]].map(x=><button className={active===x[2]?"active":""} onClick={()=>go(x[2])} key={x[2]}><strong>{x[0]}</strong><span>{x[1]}</span></button>)}</div>}
function Home({go}){
 const[query,setQuery]=useState("");
 return <><Header go={go}/><main>
  <section className="hero"><div className="heroGlow"/><span className="eyebrow">منصة التعلم العربية للطلاب والطموحين</span><h1>تعلّم بذكاء.<br/><em>ابنِ مستقبلك.</em></h1><p>دورات عملية، منح وفرص، مسابقات وفعاليات — كل ما تحتاجه لتتقدم خطوة كل يوم.</p><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث عن دورة، منحة، مسابقة..." /><button onClick={()=>go("/catalog")}>بحث</button></div><div className="quick"><span>مقترح:</span><button onClick={()=>go("/catalog")}>Python</button><button onClick={()=>go("/catalog")}>تحليل البيانات</button><button onClick={()=>go("/scholarships")}>منح</button></div></section>
  <section className="announcement"><div><small>فرصة جديدة</small><h3>ابدأ رحلة التعلم وحقق أول إنجاز لك</h3><p>تابع تقدمك واحصل على شهادات عند إكمال المسارات.</p></div><button onClick={()=>go("/catalog")}>استكشف الدورات</button></section>
  <section className="section twin"><CatalogColumn go={go}/><ScholarshipColumn go={go}/></section>
  <section className="stats"><div><b>12K+</b><span>متعلم نشط</span></div><div><b>180+</b><span>دورة ومسار</span></div><div><b>65+</b><span>منحة وفرصة</span></div><div><b>40+</b><span>مسابقة وفعالية</span></div></section>
 </main><BottomNav go={go}/></>
}
function CatalogColumn({go}){return <div className="column"><SectionHead title="دورات مميزة" icon="▤" action={()=>go("/catalog")}/><div className="cards">{courses.slice(0,2).map(c=><CourseCard c={c} go={go} key={c.id}/>)}</div></div>}
function ScholarshipColumn({go}){return <div className="column"><SectionHead title="المنح والفرص" icon="✦" action={()=>go("/scholarships")}/><div className="cards">{["منحة تدريب صيفي للطلاب","برنامج رواد المستقبل التقني"].map((x,i)=><div className="scholarCard" key={x}><div className="chip">ينتهي خلال {i?18:7} يوم</div><div className="schIcon">✦</div><h3>{x}</h3><p>{i?"تدريب عملي وشهادة معتمدة":"برنامج تدريبي وفرصة للتطوير المهني"}</p><div className="tags"><span>طلاب</span><span>{i?"تدريب":"منحة"}</span></div><button onClick={()=>go("/scholarships")}>عرض التفاصيل</button></div>)}</div></div>}
function SectionHead({title,icon,action}){return <div className="sectionHead"><button onClick={action}>عرض الكل ←</button><h2>{title} <i>{icon}</i></h2></div>}
function CourseCard({c,go}){return <article className="courseCard"><div className="courseImage" style={{background:"linear-gradient(135deg,"+c.color+",#061a3a)"}}><span>{c.cat}</span><b>{c.title.split(" ").slice(0,2).join(" ")}</b></div><div className="courseBody"><h3>{c.title}</h3><p>{c.level} · {c.lessons} درس · {c.duration}</p><div className="progress"><span style={{width:c.progress+"%"}}/></div><div className="courseFoot"><small>{c.progress?c.progress+"% مكتمل":"ابدأ الآن"}</small><button onClick={()=>go("/course")}>{c.progress?"متابعة":"ابدأ الدورة"}</button></div></div></article>}

function Catalog({go}){return <><Header go={go} active="الدورات"/><main className="page"><div className="pageTitle"><span>المكتبة التعليمية</span><h1>اكتشف <em>الدورات</em></h1><p>تعلم مهارات مطلوبة بمسارات عملية مصممة للطلاب.</p></div><div className="filters"><input placeholder="ابحث في الدورات..." /><button className="filterActive">الكل</button>{["برمجة","ذكاء اصطناعي","تحليل البيانات","تطوير الويب"].map(x=><button key={x}>{x}</button>)}</div><div className="courseGrid">{courses.concat(courses.slice(0,2)).map((c,i)=><CourseCard c={c} go={go} key={c.id+"-"+i}/>)}</div></main><BottomNav go={go} active="/catalog"/></>}
function Scholarships({go}){return <><Header go={go} active="المنح والفرص"/><main className="page"><div className="pageTitle"><span>فرصتك القادمة</span><h1>المنح <em>والفرص</em></h1><p>اكتشف فرص التدريب والمنح والمسابقات المناسبة لك.</p></div><div className="opps">{["منحة تدريب صيفي للطلاب","برنامج رواد المستقبل التقني","منحة جامعة المستقبل","تدريب تحليل البيانات للشباب"].map((x,i)=><article className="opp" key={x}><div className="oppTop"><span>جديد</span><b>✦</b></div><h2>{x}</h2><p>فرصة تطوير مهارات، تدريب عملي وشهادة — متاحة للطلاب والمهتمين بالتقنية.</p><div><small>📅 آخر موعد: {10+i*6} أكتوبر</small><small>📍 مصر · أونلاين</small></div><button onClick={()=>go("/scholarships/"+(i+1))}>التفاصيل</button></article>)}</div></main><BottomNav go={go} active="/scholarships"/></>}
function Dashboard({go}){return <><Header go={go}/><main className="dashboard page"><div className="dashHero"><div><span>مرحباً بك مجدداً</span><h1>أهلاً بك في <em>لوحتك</em></h1><p>أكمل من حيث توقفت واستمر في التقدم.</p></div><div className="ring"><b>43%</b><small>تقدمك</small></div></div><div className="dashGrid"><section className="panel wide"><div className="panelHead"><h2>دوراتي الحالية</h2><button onClick={()=>go("/catalog")}>كل الدورات</button></div>{courses.slice(0,3).map(c=><div className="enrolled" key={c.id}><div className="miniCover" style={{background:c.color}}>ك</div><div className="grow"><h3>{c.title}</h3><div className="progress"><span style={{width:c.progress+"%"}}/></div><small>{c.progress}% · {c.lessons} درس</small></div><button onClick={()=>go("/course")}>متابعة</button></div>)}</section><section className="panel"><h2>إحصائيات التعلم</h2><div className="metrics"><b>18<span>ساعة تعلم</span></b><b>7<span>شهادات</span></b><b>32<span>إنجازاً</span></b></div></section><section className="panel"><h2>آخر الإشعارات</h2>{["تم فتح درس جديد في Python","شهادة جديدة جاهزة للتحميل","منحة تناسب اهتماماتك"].map(x=><div className="notice" key={x}><i>•</i><span>{x}<small>منذ ساعتين</small></span></div>)}</section></div></main><BottomNav go={go} active="/dashboard"/></>}
function Profile({go}){return <><Header go={go}/><main className="page profile"><div className="profileCard"><div className="avatar">أ</div><h1>أحمد محمد</h1><p>طالب · مهتم بالبرمجة والذكاء الاصطناعي</p><div className="profileStats"><span><b>7</b>دورات</span><span><b>4</b>شهادات</span><span><b>32</b>إنجاز</span></div></div><div className="settings panel"><h2>إعدادات الحساب</h2>{["المعلومات الشخصية","الأمان وكلمة المرور","الإشعارات","الخصوصية"].map(x=><button key={x}>{x}<span>←</span></button>)}</div></main><BottomNav go={go} active="/profile"/></>}
function Course({go}){return <><Header go={go} active="الدورات"/><main className="coursePage"><section className="courseHero"><button onClick={()=>go("/catalog")}>← العودة للدورات</button><div className="courseHeroContent"><div><span className="pill">برمجة · مبتدئ</span><h1>أساسيات البرمجة بلغة بايثون</h1><p>تعلم أساسيات Python من الصفر وحتى بناء مشاريع عملية.</p><div className="courseMeta"><span>18 درس</span><span>4س 30د</span><span>★ 4.9</span></div><button className="goldBtn" onClick={()=>go("/course/lesson")}>متابعة الدورة</button></div><div className="coursePoster">PY<br/><small>THON</small></div></div></section><section className="courseLayout"><div className="panel"><h2>محتوى الدورة</h2>{lessons.map((l,i)=><button className={i===2?"lesson active":"lesson"} key={i} onClick={()=>i===2&&go("/course/lesson")}><span>{l[0]}</span><small>{l[1]}</small><b>{l[2]}</b><i>{i<2?"مكتمل":i===2?"تشاهد الآن":"مقفل"}</i></button>)}</div><aside className="panel courseSide"><h2>تقدم الدورة</h2><div className="bigRing">43%</div><p>أكملت 7 من 18 درساً</p><button onClick={()=>go("/course/quiz")}>اذهب للاختبار</button></aside></section></main><BottomNav go={go} active="/catalog"/></>}
function Lesson({go}){return <><Header go={go}/><main className="lessonPage"><div className="lessonTop"><button onClick={()=>go("/course")}>← أساسيات Python</button><span>الدرس 5 من 18 · 43%</span></div><div className="video"><div className="play">▶</div><div className="videoLabel">الحلقات التكرارية</div></div><article className="lessonText"><span className="pill">الوحدة 2 · الأساسيات</span><h1>الحلقات التكرارية</h1><p>في هذا الدرس ستتعلم كيف تكرر تنفيذ الأوامر باستخدام for و while، وكيف تختار الحلقة المناسبة لكل حالة.</p><pre>{'for i in range(1, 4):\\n    print(i)'}</pre><h2>متى نستخدم الحلقات؟</h2><p>عندما تحتاج إلى تنفيذ نفس مجموعة التعليمات أكثر من مرة، تساعدك الحلقات على كتابة كود أبسط وأكثر وضوحاً.</p><button className="goldBtn" onClick={()=>go("/course/quiz")}>اختبر فهمك ←</button></article></main><BottomNav go={go}/></>}
function Quiz({go}){const[n,setN]=useState(0),[selected,setSelected]=useState(null),[score,setScore]=useState(0);const q=questions[n];function next(){if(selected===q.correct)setScore(s=>s+1);if(n<questions.length-1){setN(n+1);setSelected(null)}else go("/course/results?score="+(score+(selected===q.correct?1:0)))}return <><Header go={go} active="الدورات"/><main className="quizPage"><div className="quizHeader"><button onClick={()=>go("/course")}>← العودة</button><div><b>أساسيات البرمجة بلغة بايثون</b><small>الدرس 5: الحلقات التكرارية</small></div><span>43%</span></div><div className="quizLayout"><section className="quizMain"><div className="quizProgress"><span>دورة بايثون المتقدمة</span><b>السؤال {n+1} من {questions.length}</b><div><i style={{width:((n+1)/questions.length)*100+"%"}}/></div></div><h1>{q.q}</h1><pre>{q.code}</pre><div className="answers">{q.a.map((a,i)=><button className={selected===i?"selected":""} onClick={()=>setSelected(i)} key={a}><b>{["أ","ب","ج","د"][i]}</b><span>{a}</span></button>)}</div><div className="quizActions"><button onClick={()=>n?setN(n-1):go("/course")}>السابق</button><button className="goldBtn" disabled={selected===null} onClick={next}>{n===questions.length-1?"إنهاء الاختبار":"التالي"}</button></div></section><aside className="path"><h2>منهج الدورة</h2><p>الوحدة 2: الأساسيات الحقيقية</p>{lessons.map((l,i)=><div className={i===2?"active":""} key={i}><span>{l[0]}</span><small>{l[1]}</small><b>{l[2]}</b></div>)}</aside></div></main><BottomNav go={go}/></>}
function Results({go}){return <><Header go={go}/><main className="resultPage page"><div className="resultCard"><div className="trophy">✓</div><span>أحسنت! أكملت الاختبار</span><h1>نتيجتك <em>ممتازة</em></h1><div className="score">2<small>/ 3</small></div><p>واصل التعلم وجرّب الدرس التالي.</p><button className="goldBtn" onClick={()=>go("/course")}>العودة للدورة</button></div></main><BottomNav go={go}/></>}
function Auth({go}){const[login,setLogin]=useState(true);return <main className="auth"><div className="authCard"><button className="authBrand" onClick={()=>go("/")}>خ</button><h1>{login?"مرحباً بعودتك":"أنشئ حسابك"}</h1><p>{login?"سجّل الدخول لمتابعة رحلة التعلم":"ابدأ رحلة التعلم مع أكاديمية خوارزم"}</p>{!login&&<input placeholder="الاسم بالكامل"/>}<input placeholder="البريد الإلكتروني"/><input type="password" placeholder="كلمة المرور"/><button className="goldBtn">{login?"تسجيل الدخول":"إنشاء الحساب"}</button><div className="switch">{login?"ليس لديك حساب؟":"لديك حساب بالفعل؟"} <button onClick={()=>setLogin(!login)}>{login?"إنشاء حساب":"تسجيل الدخول"}</button></div></div></main>}

function App(){
 const[path,setPath]=useState(window.location.pathname);
 function go(p){window.history.pushState({},'',p);setPath(p);window.scrollTo(0,0)}
 React.useEffect(()=>{const f=()=>setPath(window.location.pathname);window.addEventListener("popstate",f);return()=>window.removeEventListener("popstate",f)},[]);
 if(path==="/")return <Home go={go}/>;if(path==="/catalog")return <Catalog go={go}/>;if(path.startsWith("/scholarships"))return <Scholarships go={go}/>;if(path==="/dashboard")return <Dashboard go={go}/>;if(path==="/profile")return <Profile go={go}/>;if(path==="/login"||path==="/register")return <Auth go={go}/>;if(path==="/course/lesson")return <Lesson go={go}/>;if(path==="/course/quiz")return <Quiz go={go}/>;if(path.startsWith("/course/results"))return <Results go={go}/>;if(path==="/course")return <Course go={go}/>;return <Home go={go}/>
}
createRoot(document.getElementById("root")).render(<App/>);